/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthenticationRouteImport } from './routes/_authentication'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutChatRouteImport } from './routes/_layout/_chat'
import { Route as AuthenticationVerificationRouteImport } from './routes/_authentication/verification'
import { Route as AuthenticationSignupRouteImport } from './routes/_authentication/signup'
import { Route as AuthenticationLoginRouteImport } from './routes/_authentication/login'
import { Route as LayoutChatChatNewRouteImport } from './routes/_layout/_chat/chat/new'
import { Route as LayoutChatChatChatIdRouteImport } from './routes/_layout/_chat/chat/$chatId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthenticationVerificationRoute =
  AuthenticationVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticationRoute,
  } as any)
const AuthenticationSignupRoute = AuthenticationSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthenticationRoute,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticationRoute,
} as any)
const LayoutChatChatNewRoute = LayoutChatChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => LayoutChatRoute,
} as any)
const LayoutChatChatChatIdRoute = LayoutChatChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => LayoutChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthenticationLoginRoute
  '/signup': typeof AuthenticationSignupRoute
  '/verification': typeof AuthenticationVerificationRoute
  '/chat/$chatId': typeof LayoutChatChatChatIdRoute
  '/chat/new': typeof LayoutChatChatNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthenticationLoginRoute
  '/signup': typeof AuthenticationSignupRoute
  '/verification': typeof AuthenticationVerificationRoute
  '/chat/$chatId': typeof LayoutChatChatChatIdRoute
  '/chat/new': typeof LayoutChatChatNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authentication': typeof AuthenticationRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_authentication/login': typeof AuthenticationLoginRoute
  '/_authentication/signup': typeof AuthenticationSignupRoute
  '/_authentication/verification': typeof AuthenticationVerificationRoute
  '/_layout/_chat': typeof LayoutChatRouteWithChildren
  '/_layout/_chat/chat/$chatId': typeof LayoutChatChatChatIdRoute
  '/_layout/_chat/chat/new': typeof LayoutChatChatNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/verification'
    | '/chat/$chatId'
    | '/chat/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verification'
    | '/chat/$chatId'
    | '/chat/new'
  id:
    | '__root__'
    | '/'
    | '/_authentication'
    | '/_layout'
    | '/_authentication/login'
    | '/_authentication/signup'
    | '/_authentication/verification'
    | '/_layout/_chat'
    | '/_layout/_chat/chat/$chatId'
    | '/_layout/_chat/chat/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationRoute: typeof AuthenticationRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_chat': {
      id: '/_layout/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_authentication/verification': {
      id: '/_authentication/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticationVerificationRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/signup': {
      id: '/_authentication/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthenticationSignupRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_authentication/login': {
      id: '/_authentication/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof AuthenticationRoute
    }
    '/_layout/_chat/chat/new': {
      id: '/_layout/_chat/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof LayoutChatChatNewRouteImport
      parentRoute: typeof LayoutChatRoute
    }
    '/_layout/_chat/chat/$chatId': {
      id: '/_layout/_chat/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof LayoutChatChatChatIdRouteImport
      parentRoute: typeof LayoutChatRoute
    }
  }
}

interface AuthenticationRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationSignupRoute: typeof AuthenticationSignupRoute
  AuthenticationVerificationRoute: typeof AuthenticationVerificationRoute
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationSignupRoute: AuthenticationSignupRoute,
  AuthenticationVerificationRoute: AuthenticationVerificationRoute,
}

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren,
)

interface LayoutChatRouteChildren {
  LayoutChatChatChatIdRoute: typeof LayoutChatChatChatIdRoute
  LayoutChatChatNewRoute: typeof LayoutChatChatNewRoute
}

const LayoutChatRouteChildren: LayoutChatRouteChildren = {
  LayoutChatChatChatIdRoute: LayoutChatChatChatIdRoute,
  LayoutChatChatNewRoute: LayoutChatChatNewRoute,
}

const LayoutChatRouteWithChildren = LayoutChatRoute._addFileChildren(
  LayoutChatRouteChildren,
)

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationRoute: AuthenticationRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
